Add value check constraints for database columns
vu-vibedosa/apsitvarkom-be pull request #130
Opened 2022-12-02 22:45 UTC by 6ar8nas

## What was done

- Changed the way we store Enum values in the db to the [default](https://dev.mysql.com/doc/refman/8.0/en/enum.html#:~:text=An%20ENUM%20is%20a%20string,specification%20at%20table%20creation%20time.) SQL behavior - using strings.
- Added check constraints for all PollutedLocation values. These are to be expanded with #126 

Integration testing, as was described in the issue, is unavailable using in-memory testing. Tested the behavior manually - everything seems to work fine.

2022-12-03 12:50 UTC, BaVilius approved these changes
Looks good to me as far as grammar and cleanliness of the code goes. However I am not familiar with the ModelBuilder class.

2022-12-04 12:17 UTC, BenasB requested changes

2022-12-04 12:17 UTC, BenasB commented on Apsitvarkom.DataAccess/PollutedLocationContext.cs
> +            .HasCheckConstraint("CK_PollutedLocation_Severity", "\"Severity\" in ('Low', 'Moderate', 'High')")
> `'Low', 'Moderate', 'High'`

You can probably get these values dynamically from the enum, right? We should not hard code them if we can

2022-12-04 16:09 UTC, BenasB approved these changes

2022-12-04 16:50 UTC, merged